apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-deep-dive-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online
  template:
    metadata:
      labels:
        app: online
  spec:
    containers:
    - image: gcr.io/google-containers/echoserver:1.10
      name: gke-deep-dive-app
      ports:
      - name: http
        containerPort: 8080
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8080
          scheme: HTTP
